version: "3"
services:
        app:
                build:
                        context: .
                        dockerfile: Dockerfile-app
                ports:
                        - "3002:3002"
                network_mode: "host"