version: "3"
services:
        emprunt-app:
                image: ws-emprunt-app
                depends_on:
                        - db
                ports:
                        - "3000:3000"
                networks: 
                        ETH:
                                ipv4_address: 10.5.0.2
        emprunt-db:
                image: ws-emprunt-db
                environment:
                        POSTGRES_USER: emprunt
                        POSTGRES_PASSWORD: emprunt
                        POSTGRES_DB: emprunt
                networks: 
                        ETH:
                                ipv4_address: 10.5.0.3
networks:
        ETH:
                driver: bridge
                ipam:
                        config:
                        - 
                                subnet: 10.5.0.0/16
