version: "3"
services:
        app:
                build:
                        context: .
                        dockerfile: Dockerfile-app
                depends_on:
                        - db
                ports:
                        - "3000:3000"
                networks: 
                        ETH:
                                ipv4_address: 10.5.0.2
        db:
                build: 
                        context: .
                        dockerfile: Dockerfile-db
                environment:
                        POSTGRES_USER: ws2
                        POSTGRES_PASSWORD: passwd2
                        POSTGRES_DB: service
                networks: 
                        ETH:
                                ipv4_address: 10.5.0.3
networks:
        ETH:
                driver: bridge
                ipam:
                        config:
                        - 
                                subnet: 10.5.0.0/16