version: "3"
services:
        livre-app:
                image: ws-livre-app
                depends_on:
                        - db
                ports:
                        - "3001:3001"
                networks: 
                        ETH2:
                                ipv4_address: 10.6.0.2
        livre-db:
                image: ws-livre-db
                environment:
                        POSTGRES_USER: livre
                        POSTGRES_PASSWORD: livre
                        POSTGRES_DB: livre
                networks: 
                        ETH2:
                                ipv4_address: 10.6.0.3
networks:
        ETH2:
                driver: bridge
                ipam:
                        config:
                        - 
                                subnet: 10.6.0.0/16